default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5 %>

development:
  <<: *default
  database: outdoor-blog_development

test:
  <<: *default
  database: outdoor-blog_test

production:
  <<: *default
  database: outdoor-blog_production
